### ISSUE TITLE
MSVC W4 warnings and strndup not found

### ISSUE THREAD

**Issue by siltutorials** [cktan/tomlc99#1]
When compiling toml.c on windows x64 Microsoft Visual Studios Compiler on warning level 4 (/W4) there are a lot of implicit cast warnings. (int64 or int not explicitly cast to char, etc.).

Another unrelated topic: windows standard libraries do not seem to have a definition for strndup. It's possible I'm missing something here though?

![tomlerrors](https://user-images.githubusercontent.com/4468838/28903727-7873131c-77bb-11e7-9c48-a779185f9a60.png)

**Comment by cktan** [comment]
I fixed some of the warnings, and provided strndup() for WIN32. Send me the output from your compiler for the other warnings, and I will try to clean it up. 

Thanks!
