### ISSUE TITLE
question: reason for "len" in toml_utf8_to_ucs?

### ISSUE THREAD

**Issue by gregfi** [cktan/tomlc99#19]
What is the reason for the "len" variable in toml_utf8_to_ucs? Is it to prevent parsing beyond the null terminator? Thanks.

**Comment by cktan** [comment]
First few bits in the first byte indicates the length of the unicode character, which could range from 1 to 5. Once we know the length of the unicode character, we must make sure that there the whole char is fully stored in the passed in string buffer. 

i.e. if the first bits indicate a 3-byte unicode char, and we have only 2 bytes remaining in the buffer, we return an error.
