### ISSUE TITLE
TOML encode with TOMLC99

### ISSUE THREAD

**Issue by keito940** [cktan/tomlc99#23]
Hi.
I was looking for tools to use TOML in C and found something like this.
It seems that TOML can be read, but if TOML can be written, what can be done in C?

**Comment by keito940** [comment]
I solved it after reading the manual carefully.

**Comment by keito940** [comment]
I'm sorry to close and reopen.
I'm sure you really want to support encoding.

**Comment by cktan** [comment]
I think you meant the library should support writes. In that case, I would like to keep this lib small and easy to use, and be really good at read-only. Sorry.
