### ISSUE TITLE
Getting strings prints quotation marks

### ISSUE THREAD

**Issue by DerekCresswell** [cktan/tomlc99#38]
I've got something like this :
```cpp
toml_array_t* profileNames = toml_array_in(table, "profileNames");
const char* nameOne = toml_raw_at(profileNames, 0);
```

Where profile names is :
```toml
profileNames = [
    "personal",
    "work"
]
```

In this case when I print out `nameOne` I get `"personal"` when I would expect `personal`. It seems like when getting a string literal it should not include the first and last quotation marks.

**Comment by turbo** [comment]
`nameOne` holds the raw memory parsed from the key. You need to convert the raw value to a proper type with `toml_rtos`.

**Comment by DerekCresswell** [comment]
Oh geez, I glossed right over that. Could probably use some more thorough  documentation.

Would you know why the default wouldn't return the string? In my mind it would make more sense to have the raw be a separate function.

**Comment by turbo** [comment]
That would be an overhead, it makes sense in some situations to keep around the raw pointer, e.g. if you don't know for a fact it will be accessed. Strings are also a deceivingly simple example. What about timestamps? Should that rather large struct be allocated automatically every time? 

It might make sense to have a separate API that's more "automatic". But FWIW I just wrote LuaJIT FFI bindings for this library and had no issues with the API as it is. You just need to consider anything returned from `toml_*` as opaque pointers unless processed by `toml_rto*`.

**Comment by turbo** [comment]
But you're right on the documentation. It might make sense to `typedef` the return type from `raw_at` to something that doesn't look like a standard string and add documentation about raw values to the library. Maybe send a PR? The author doesn't seem to be very active anymore.

**Comment by DerekCresswell** [comment]
That makes sense, thank you.
I'll see about making a PR for that, hopefully it can get noticed, I always hate seeing a project falling to the way side.

**Comment by cktan** [comment]
@turbo @DerekCresswell sorry guys, I should setup the repo properly so I get notified when someone post issues or push fixes.
