### ISSUE TITLE
Better support for nostdlib (no Glibc) environments

### ISSUE THREAD

**Issue by dimakuv** [cktan/tomlc99#44]
Thank you @cktan for the great TOML library!

We would like to use your TOML parser to parse configuration files in the Graphene framework (https://github.com/oscarlab/graphene). However, Graphene is a very low-level Linux emulation framework and thus sits below the Standard C Library (Glibc/Musl) and is built with `-nostdlib` .

Graphene provides some utility functions like `malloc`/`calloc`/`memcpy`/`free`/`strcmp` and so on (basically a small subset of memory management and string utilities). However, your TOML implementation currently relies on:
1. `ctype.h` functions: `toupper()`, `isalnum()`, `isdigit()`. These can be easily replaced with actual implementations.
2. `strtoll()` -- on 64-bit systems, this is just the alias to `strtol()`, easy via macros.
3. `realloc()` -- Graphene doesn't have realoc (complicated reasons...), but your TOML code seems to use the same simple extend-memory pattern, so easy to replace with `malloc + memcpy + free`.
4. `setjmp()`/`longjmp()` -- Graphene doesn't have these functions. These are the hardest ones to change, it took me significant modifications of your code to revert to the "classical C" style of propagating error codes to the caller.

I forked your TOML repo and introduced the changes described above: https://github.com/dimakuv/tomlc99/commits/master.

With these changes, your TOML library becomes very self-contained and requires only a handful of standard functions. You can review the changes via my link above.

I wonder if this is something you'd be willing to merge? We in the Graphene community would be happy to download-and-use the master of your repository (maybe with minimal patching). But right now the changes are significant. I could prepare a sequence of PRs for merge if you think my changes are reasonable.

**Comment by cktan** [comment]
It seems the biggest offenders are setjmp and longjmp, and I also think
they are a bit heavy handed here. I was reluctant to change it because
changing it would involve significant modifications that would take time to
shakedown and stabilize. That said, I think we can first merge your code in
a separate branch, starting with setjmp/longjmp removal only.

**Comment by dimakuv** [comment]
Thank you @cktan for merging/implementing the most significant changes and very quick responses!
