### ISSUE TITLE
RFE: slow to large large TOML files

### ISSUE THREAD

**Issue by FGasper** [cktan/tomlc99#52]
https://gist.githubusercontent.com/feeeper/2197d6d734729625a037af1df14cf2aa/raw/2f22b120e476d897179be3c1e2483d18067aa7df/config.toml

^^ When I try to parse that file with this library, it takes quite a while … the pure-Perl parser [TOML::Tiny](https://metacpan.org/pod/TOML::Tiny) is actually noticeably faster.

I dug in a bit and see that it’s doing a lot of strchr …
```
~/code/tomlc99 $ google-pprof --text a.out ./prof.out
Using local file a.out.
Using local file ./prof.out.
Total: 1154 samples
    1120  97.1%  97.1%     1120  97.1% strchr
      12   1.0%  98.1%       12   1.0% memcpy
       7   0.6%  98.7%        7   0.6% next_token
       2   0.2%  98.9%        2   0.2% 0xffff0fe0
       2   0.2%  99.0%        2   0.2% scan_string
       2   0.2%  99.2%        2   0.2% scan_time
       1   0.1%  99.3%        1   0.1% __libc_malloc
       1   0.1%  99.4%        1   0.1% check_key
       1   0.1%  99.5%        1   0.1% normalize_key
       1   0.1%  99.6%        1   0.1% operator delete[]
       1   0.1%  99.7%        1   0.1% parse_select
       1   0.1%  99.7%        1   0.1% set_token
       1   0.1%  99.8%        1   0.1% tcmalloc::CentralFreeList::Populate
       1   0.1%  99.9%        2   0.2% tcmalloc::CentralFreeList::RemoveRange
       1   0.1% 100.0%        1   0.1% toml_array_in
       0   0.0% 100.0%        1   0.1% tcmalloc::CentralFreeList::FetchFromOneSpansSafe
       0   0.0% 100.0%        2   0.2% tcmalloc::ThreadCache::FetchFromCentralCache
```
Does that maybe offer any hint of how this might be improved?

tomlc99 is much faster than TOML::Tiny for small & medium TOML files; I’d like to see if it can be faster for large ones, too.

Thank you!

**Comment by cktan** [comment]
thanks for the fix. I will take a look.

**Comment by cktan** [comment]
Thanks for submitting the patch. 

I was able to do it another way. Please check 06e2fceedff563a656c4b5b5abfe5c99a214fa75 .

Thanks,
-cktan
