### ISSUE TITLE
Value of “0000000” isn’t caught as invalid syntax.

### ISSUE THREAD

**Issue by FGasper** [cktan/tomlc99#54]
The spec says “Leading zeros are not allowed.” But if I create a file `fg.toml`:
```
SSL_DEFAULT_KEY_TYPE='system'
STARTDATE=0000000000
```
… and feed it to toml_cat, I get:
```
> ./toml_cat fg.toml
{
  SSL_DEFAULT_KEY_TYPE = "system",
ERROR: unable to decode value in table
```

**Comment by cktan** [comment]
Yeah, as it stands today, the parser does not detect value error. It is detected later, after parsing, when the value is retrieved.

**Comment by FGasper** [comment]
That makes sense. I’ll close this.

Incidentally: https://metacpan.org/pod/TOML::XS
