### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by codecat** [cktan/tomlc99#59]
Looking at the API I don't think this library actually knows what type a value in a table is. I'd like to iterate over all keys in a table and determine their type directly. This isn't possible right now, is it?

**Comment by cktan** [comment]
No. The API assumes the caller knows the type of the value, which is
customary when getting config values out of config files.

**Comment by codecat** [comment]
Indeed, a fair assumption. So would a feature like this be out of scope for this project?

**Comment by cktan** [comment]
Take a look at toml_json.c. It tries to fit a type on the value
algorithmically.

**Comment by codecat** [comment]
Ah, I did not realize the raw to X functions actually returned whether it was successful or not. That helps! I will do some testing with this.

**Comment by codecat** [comment]
That seems to work well for my purposes, thanks!
