### ISSUE TITLE
BurntSushi Tests Fail due to deprecation in go get

### ISSUE THREAD

**Issue by mcb2003** [cktan/tomlc99#62]
When running `test1/build.sh`, go outputs the following notice:

```
$ bash build.sh 
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

As expected, running `run.sh` after this fails:

```
$ bash run.sh 
run.sh: line 5: ./toml-test: No such file or directory
```

**Comment by marzer** [comment]
> FYI, the burnt sushi tests are a bit outdated, and I may drop them soon. E.g. v1 toml allows mixed types arrays, but burnt sushi thanks they should not be allowed.

That is [no longer true](https://github.com/BurntSushi/toml-test) as the project has a new maintainer. It is now regularly updated and tests many TOML v1.0 features.

In fact, the recent discussion on [this issue](https://github.com/toml-lang/toml/issues/585) on toml-lang/toml suggests that the newly-maintained BurntSushi/toml-test will actually come to serve as the 'official' one in some capacity.
