### ISSUE TITLE
Writing to TOML file?

### ISSUE THREAD

**Issue by Frityet** [cktan/tomlc99#66]
Hello, where could I find examples of writing to a TOML file with this library?

**Comment by cktan** [comment]
Hi, 

I am sorry we don't support writing to TOML file. The library is meant for apps to read config files.

**Comment by albert-tomanek** [comment]
@cktan Would you potentially accept a PR for one?

**Comment by cktan** [comment]
Sorry, I think it is best to restrict the LOC for ease of maintenance.
