### ISSUE TITLE
How to free string and timestamp return by this lib?

### ISSUE THREAD

**Issue by tisonkun** [cktan/tomlc99#89]
```c
struct toml_datum_t {
  int ok;
  union {
    toml_timestamp_t *ts; /* ts must be freed after use */
    char *s;              /* string value. s must be freed after use */
    int b;                /* bool value */
    int64_t i;            /* int value */
    double d;             /* double value */
  } u;
};
```

It seems that `s` and `ts` should be freed by the user. But `xfree` is internal, `toml_free(toml_table_t *tab)` only for table. Then how can I free these returned value?

Also, it seems the returned value of `toml_array_in` and `toml_table_in` need not to be freed?

**Comment by cktan** [comment]
On Sun, Nov 26, 2023, 5:56 AM tison ***@***.***> wrote:

> struct toml_datum_t {
>   int ok;
>   union {
>     toml_timestamp_t *ts; /* ts must be freed after use */
>     char *s;              /* string value. s must be freed after use */
>     int b;                /* bool value */
>     int64_t i;            /* int value */
>     double d;             /* double value */
>   } u;
> };
>
> It seems that s and ts should be freed by the user. But xfree is
> internal, toml_free(toml_table_t *tab) only for table. Then how can I
> free these returned value?
>
Just call free() if you didn't override the malloc/free functions.

Also, it seems the returned value of toml_array_in and toml_table_in need
> not to be freed?
>
Yes. See the toml_sample.c file for usage.

**Comment by tisonkun** [comment]
Thank you! And if I override malloc/free function, use the override version instead?

BTW, is it possible to use customized allocator in a concurrent context? (Seems `toml_set_memutil` modifies globally)

**Comment by cktan** [comment]
On Sun, Nov 26, 2023, 7:02 AM tison ***@***.***> wrote:

> Thank you! And if I override malloc/free function, use the override
> version instead?
>
Yup.

BTW, is it possible to use customized allocator in a concurrent context?
> (Seems toml_set_memutil modifies globally)
>
No. Overrides is global for simplicity sake.

**Comment by tisonkun** [comment]
Thanks for your clarification! It's clear to me now.
