### ISSUE TITLE
Request - include print capability in core library

### ISSUE THREAD

**Issue by dmjones** [cktan/tomlc99#9]
I'm using your library to parse TOML without trouble, thanks.

I notice `toml_cat.c` contains logic for printing a parsed TOML file. Could you add that functionality into `toml.c/h` so that printing to a file pointer is supported?

My app will read and write the config file, so the ability to write is needed. But you have 95% of what is needed already.

**Comment by cktan** [comment]
@dmjones Thanks for checking out tomlc99. I would like to keep toml.c as small as possible; you are welcome to pull code out of toml_cat.c for your purpose. Would that be acceptable?
